### PR TITLE
Updated several operations in SIMBAD

### PR DESCRIPTION
**Pull request by hlasimpk**
Added
- Added in code that uses pointless to reindex mtz files
- EXE_EXT calls to all executable commands to allow for windows compatibility
- Completely reformatted all pyjob calls to use version 0.2.0 and updated dependencies list.
- Function to get the sequence from a pdb file
- Function to generate ensemble database

 Changed
- Replaced CCTBX code that checked the columns in the input MTZ with MrBump code as CCTBX was giving errors for certain input MTZs. 
- Replaced `simbad.util.mtz_util.get_labels` with a class called `simbad.util.mtz_util.GetLabels`. This returns more types of input labels and simplifies how the labels are passed into other functions.
- Updated test cases affected by changes
- `simbad.util.mtz_util.GetLabels` was changed to use miller arrays and is therefore more robust when handling columns with non-standard names
- `simbad.rotsearch.phaser_search` changed to rank models by RFZ rather than LLG.

### CODE REVIEW

**Comment by hlasimpk** [comment]
It's all been tested on my unit tests and my example test cases and works. The main thing to keep an eye on is how the updated MTZ preparation step affects things.

**Comment by rmk65** [comment]
Do you plan to make a version release with this code. I could do a few quick tests with it in situ in CCP4.

**Comment by hlasimpk** [comment]
Yeah, was about to do that now, I can hold off if you want to do the in situ tests. Note: you'll require the latest version of Pyjob. When this goes into CCP4 it will have to go in alongside or after pyjob.

**Comment by rmk65** [comment]
If you do a release I can update my local CCP4 build to incorporate it in the compilation (via jhbuild).

**Pull request merged**
